language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t amaterasus/refactored-octo-broccoli -f Dockerfile.dev .


script:
    - docker run -e CI=true amaterasus/refactored-octo-broccoli npm run test